# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml

# Redundant returns add legibility for developers used to other languages
Style/RedundantReturn:
  Enabled: false

# Don't enforce any particular name for block params
SingleLineBlockParams:
  Enabled: false

# The general YaST agreement is 100 characters, so it fits into standard
# resolutions and Github's pull request view. But let's open the threshold a
# little bit
Metrics/LineLength:
  Max: 105

Metrics/BlockLength:
  # rspec is know for big blocks as DSL
  Exclude:
    - test/**/*

# some storage API have size method, but without empty? method
# for details see https://github.com/yast/yast-storage-ng/pull/83
Style/ZeroLengthPredicate:
  Enabled: false

# the ".freeze" attribute for the constants is not nice
Style/MutableConstant:
  Enabled: false

# this failing in storage wrapper, will need more time to adapt
Style/FrozenStringLiteralComment:
  Enabled: false

# workaround https://github.com/rubocop-hq/rubocop/issues/6861
Layout/AccessModifierIndentation:
  EnforcedStyle: indent

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - vg
    - md
    - lv
    - id
    - up
    - to
    - as

# WIP

# Offense count: 8
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'test/y2partitioner/actions/add_btrfs_test.rb'
    - 'test/y2partitioner/widgets/btrfs_devices_selector_test.rb'
    - 'test/y2storage/planned/can_be_formatted_test.rb'

# Offense count: 1
# Configuration parameters: MaximumRangeSize.
Lint/MissingCopEnableDirective:
  Exclude:
    - 'src/lib/y2storage/planned/can_be_formatted.rb'

# Offense count: 1
Lint/ReturnInVoidContext:
  Exclude:
    - 'src/lib/y2storage/proposal/lvm_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
Lint/UnneededCopEnableDirective:
  Exclude:
    - 'src/lib/y2storage/storage_manager.rb'

# Offense count: 3
Lint/UselessAssignment:
  Exclude:
    - 'src/lib/y2storage/initial_guided_proposal.rb'

# Offense count: 2
# Configuration parameters: CheckForMethodsWithNoSideEffects.
Lint/Void:
  Exclude:
    - 'src/lib/y2storage/mount_point.rb'
    - 'src/lib/y2storage/proposal/lvm_helper.rb'
