# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml

# Redundant returns add legibility for developers used to other languages
Style/RedundantReturn:
  Enabled: false

# Don't enforce any particular name for block params
SingleLineBlockParams:
  Enabled: false

# The general YaST agreement is 100 characters, so it fits into standard
# resolutions and Github's pull request view. But let's open the threshold a
# little bit
Metrics/LineLength:
  Max: 105

Metrics/BlockLength:
  # rspec is know for big blocks as DSL
  Exclude:
    - test/**/*

# some storage API have size method, but without empty? method
# for details see https://github.com/yast/yast-storage-ng/pull/83
Style/ZeroLengthPredicate:
  Enabled: false

# the ".freeze" attribute for the constants is not nice
Style/MutableConstant:
  Enabled: false
